apiVersion: v1
kind: Service
metadata:
  name: node-api
  namespace: node-api
  labels:
    app: node-api
spec:
  type: ClusterIP
  selector:
    app: node-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
