apiVersion: v1
kind: Service
metadata:
  name: python-api
  namespace: python-api
  labels:
    app: python-api
spec:
  type: LoadBalancer
  selector:
    app: python-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
